version: '3.8'
services:
  auth:
    build: ./auth-service
    ports:
      - "5000:80"   # auth reachable at http://localhost:5000
  rooms:
    build: ./rooms-service
    ports:
      - "5001:80"   # rooms reachable at http://localhost:5001
  frontend:
    image: nginx:stable
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"   # frontend at http://localhost:8080
