version: '3.8'
services:
  auth:
    build: ./auth-service
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  tasks:
    build: ./tasks-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///data/tasks.db
