name: SAST - SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- .NET part (auth-service) ---
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build auth-service
        working-directory: auth-service
        run: dotnet build --configuration Release

      # --- Python part (tasks-service) optional: run tests if any ---
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        working-directory: tasks-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- SonarCloud scan ---
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
