name: SonarCloud - .NET (auth-service)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-dotnet:
    name: Build and analyze .NET (auth-service)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Cache Sonar scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install dotnet-sonarscanner (if cache miss)
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ${{ runner.temp }}\scanner -ItemType Directory -Force
          dotnet tool install dotnet-sonarscanner --version 5.* --tool-path ${{ runner.temp }}\scanner

      - name: Begin SonarCloud analysis (in auth-service)
        working-directory: auth-service
        shell: powershell
        run: |
          $scanner = "${{ runner.temp }}\scanner\dotnet-sonarscanner"
          & $scanner begin /k:"${{ secrets.SONAR_PROJECT_KEY }}" /o:"${{ secrets.SONAR_ORGANIZATION }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      - name: Restore & Build auth-service (same folder)
        working-directory: auth-service
        shell: powershell
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: End SonarCloud analysis (in auth-service)
        working-directory: auth-service
        shell: powershell
        run: |
          $scanner = "${{ runner.temp }}\scanner\dotnet-sonarscanner"
          & $scanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
